DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS LIBRARY;
  
CREATE TABLE BOOKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  book_name VARCHAR(250) NOT NULL,
  book_description VARCHAR(250) NOT NULL,
  library_id INT NOT NULL
);

CREATE TABLE LIBRARY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  library_name VARCHAR(250) NOT NULL
);